import Head from 'next/head';
import Hero from '../components/Hero/hero';




export default function Home() {
  return (
    <div>
      <Head>
        <title>Obodai Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='WELCOME TO'/>     
    </div>
  );
}
